package com.nexus.personaldashboard.ui.navigation

enum class NavRoute {
    ONBOARDING,
    HOME,
    NOTIFICATIONS,
    AI_HUB,
    TASKS,
    SCHEDULE,
    ENTERTAINMENT,
    SETTINGS,
    SEARCH,
    ADD_TASK,
    EDIT_TASK,
    ADD_SCHEDULE,
    EDIT_SCHEDULE,
    ADD_AI_APP,
    EDIT_AI_APP,
    PRIVATE_CHAT,
    GAMES,
    GAME_XO,
    GAME_RACING,
    GAME_CONNECT_FOUR,
    GAME_QUESTIONS,
    COIN_STORE,
    ISLAMIC,
    PRAYER_TIMES,
    QURAN,
    AZKAR,
    MOOD,
    CALENDAR,
    REMINDERS,
    PROFILE,
    SPECIAL_DAYS
}
